Fixed string::replace doesn't replace multiple occurrences of longer string with shorter one
arduino/ArduinoCore-API pull request #200
Opened 2023-08-30 14:52 UTC by PiotrekB416

This pr fixes `string::replace` not replacing multiple occurrences of longer string with shorter one.
I also included unit tests from the issue

This fixes #199

2023-08-30 21:12 UTC, per1234 requested changes

2023-08-30 21:12 UTC, per1234 commented on api/String.cpp
> +        diff = 0 - diff;
```suggestion
		diff = 0 - diff;
```

Use tabs for indentation to be consistent with the established code style of the file.

2023-09-04 09:27 UTC, aentinger approved these changes
Excellent work, thank you @PiotrekB416 🚀

2023-09-04 09:27 UTC, aentinger commented on api/String.cpp
> +		diff = 0 - diff;
Ah, this line hurts 😉 . (Could it not be `abs(diff)`? However, you did not commit this crime, simply moved the line to the right position 👍 .

2023-09-04 09:27 UTC, merged